version: 2

job_defaults: &defaults
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.10.5

jobs:
  format-check:
    <<: *defaults
    steps:
      - checkout
      - run: dart format -o none --set-exit-if-changed .
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter analyze
  test:
    <<: *defaults
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter test

workflows:
  version: 2
  pull-request-validation:
    jobs:
      - test
      - analyze
      - format-check
